language: node_js
node_js:
- '7.1'
compiler: clang-3.6
env:
- CXX=clang-3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
deploy:
  provider: heroku
  api_key:
    secure: V782latNNcLnp7zEL9TIliOQbd+b5mkKatk7XssdqKY28JEnBU+hhZxHk8G48UkWpRN35159kefGBnHN0FF3a0y/xZGO0iCPQNtUhzVkne3oY4joWLWSkWjO00W73O9XuJPC77vmTrGfneem/RH6WguhjpzqmmT69CgMSoDWV2LW7GU7ByHUIgnrLmGpSeooBSrWaa+ielEw0YSWdVsiX+DmByNBhQNGfJ8SyYtzrVI4xfqFaUab8Q7mIxJUege4FXUzZxVD93vmkElpWyY2iEOXLhMyJ3umPscg+OmUk6jezYi+rtpGicxZM3vbcgPZ1pnZmZiPMsjVZdD8q18txmLn28y0vGnsSa7Udqz5s1aVWB/r5hGQUmIwDScnvi4ccrbq2c/dauk9BQyUtS9ClMerlqwq273TF1VP89/QgJt/oyjD8R8qWRB47PuoHjNc8oVj9NgmwzcAmWt7V6nI/9PSmMBhPKTtsJjePODAVzzpw7csMvgOCSFWZdbFmnuMkMBhFVLck06FKRZ6mKc25BkYeRA5zrLl7KbPOTlN9NHbnXlE3kEsiA6vH8PEF4/0o7MDgEx6l5PedLsEux8/LtHdAkmC4eE2ekNXB2sPq50UTOP4bLflgy9sO5PZ/rjOSw3WSo/ET4NKF4BiZ6DuszDMy94k7WDp/od8ayaTGRY=
  app: joules-bourne
after_success:
- 'npm run travis-coverage'
